apiVersion: apps/v1
kind: Deployment
metadata:
  name:  winning-group-test-kubectl
  namespace: winning-test
  labels:
    app: winning-group-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: winning-group-test
  template:
    metadata:
      labels:
        app: winning-group-test
    spec:
      containers:
      - name: winning-group-test-container
        image: varunmehta1986/winningroupproductapi
        resources:
          limits:
            memory: "128Mi"
            cpu:  "500m"
        ports:
        - containerPort: 80